#include <pie/errno.h>

//static struct errentry_t * ___sys_errlist[] =
//{
//	{ 0, "Operation succeeded" },
//	{ EPERM, "Operation not permitted" },
//	{ ENOENT, "No such file or directory" },
//	{ ESRCH, "No such process" },
//	{ EINTR, "Interrupted system call" },
//	{ EIO, "Input/output error" },
//	{ ENXIO, "No such device or address" },
//	{ E2BIG, "Argument list too long" },
//	{ ENOEXEC, "Invalid executable file format" },
//	{ EBADF, "Bad file descriptor" },
//	{ ECHILD, "No child processes" },
//	{ EAGAIN, "Resource temporarily unavailable" },
//	{ ENOMEM, "No buffer space available" },
//	{ EACCES, "Permission denied" },
//	{ EFAULT, "Bad address" },
//	{ EBUSY, "Device or resource busy" },
//	{ EEXIST, "File exists" },
//	{ EXDEV, "Invalid cross-device link" },
//	{ ENODEV, "No such device" },
//	{ ENOTDIR, "Not a directory" },
//	{ EISDIR, "Is a directory" },
//	{ ENFILE, "Too many open files in system" },
//	{ EMFILE, "Too many open files" },
//	{ ENOTTY, "Inappropriate ioctl for device" },
//	{ EFBIG, "File too large" },
//	{ ENOSPC, "No space left on device" },
//	{ EPIPE, "Illegal seek operation" },
//	{ EDOM, "Numerical argument out of domain" },
//	{ EDEADLK, "Deadlock encountered" },
//	{ ENAMETOOLONG,  "File name too long" },
//	{ ENOLCK, "No locks available" },
//	{ ENOSYS, "Function not implemented" },
//	{ ENOTEMPTY, "Directory not empty" },
//
//	{ EADDRINUSE, "Address already in use" },
//	{ EADDRNOTAVAIL,  "Requested socket address not available" },
//	{ EAFNOSUPPORT, "Address family not supported by protocol" },
//	{ EALREADY, "Operation already in progress" },
//	{ EBADMSG, "Bad message" },
//	{ ECANCELED, "Operation was canceled" },
//	{ ECONNABORTED, "Software caused connection abort" },
//	{ ECONNREFUSED, "Connection refused" },
//	{ ECONNRESET, "Connection reset by peer" },
//	{ EDESTADDRREQ, "Destination address required" },
//	{ EHOSTUNREACH, "No route to host" },
//	{ EIDRM, "Identifier removed" },
//	{ EINPROGRESS,  "Operation in progress" },
//	{ EISCONN, "Endpoint already connected" },
//	{ ELOOP, "Too many levels of symbolic links" },
//	{ EMSGSIZE, "Message too long" },
//	{ ENETDOWN, "Network is down" },
//	{ ENETRESET, "Network dropped connection on reset" },
//	{ ENETUNREACH, "Network is unreachable" },
//	{ ENOBUFS, "No buffer space available" },
//	{ ENODATA, "No data available" },
//	{ ENOLINK, "Link has been severed" },
//	{ ENOMSG, "No message of desired type" },
//	{ ENOPROTOOPT, "Protocol not available" },
//	{ ENOSR, "Out of streams resources" },
//	{ ENOSTR, "Device not a stream" },
//	{ ENOTCONN, "Transport endpoint is not connected" },
//	{ ENOTRECOVERABLE, "State not recoverable" },
//	{ ENOTSOCK, "Socket operation on non-socket" },
//	{ ENOTSUP, "Not supported" },
//	{ EOPNOTSUPP, "Operation not supported" },
//	{ EOTHER, "Non-POSIX error code" },
//	{ EOVERFLOW, "Value too large for defined data type" },
//	{ EOWNERDEAD, "Owner died" },
//	{ EPROTO, "Protocol error" },
//	{ EPROTONOSUPPORT, "Protocol not supported" },
//	{ EPROTOTYPE, "Wrong protocol type for socket" },
//	{ ETIME, "Timer expired" },
//	{ ETIMEDOUT, "Connection timed out" },
//	{ ETXTBSY, "Text file busy" },
//	{ EWOULDBLOCK, "Operation would block" }
//};
